version: '3.4'

services:
  sm.ecommerce.api.orders:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "6000:80"
      - "443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:ro
  sm.ecommerce.api.customers:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6001:80"


  sm.ecommerce.api.products:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6002:80"


  sm.ecommerce.api.search:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6003:80"

