version: '3.4'

services:
  sm.ecommerce.api.orders:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6000:80"
  sm.ecommerce.api.customers:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6001:80"
  sm.ecommerce.api.products:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6002:80"
  sm.ecommerce.api.search:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__Products=http://sm.ecommerce.api.products
      - Services__Customers=http://sm.ecommerce.api.customers
      - Services__Orders=http://sm.ecommerce.api.orders
    ports:
      - "6003:80"

